### ISSUE TITLE
error when i use this plugin

### ISSUE THREAD

**Issue by NElight** [cmdcolin/myvariantviewer#5]
when i use this plugin, the result show below:
<img width="1422" alt="图片" src="https://user-images.githubusercontent.com/18420368/61191976-23cdfd00-a6e3-11e9-8e0c-8272246f74eb.png">

i have the directory in plugins:
<img width="518" alt="图片" src="https://user-images.githubusercontent.com/18420368/61192014-84f5d080-a6e3-11e9-87c8-68636b5a2bb2.png">
and the jbrower_conf.json file like:
<img width="546" alt="图片" src="https://user-images.githubusercontent.com/18420368/61192021-aa82da00-a6e3-11e9-807c-5a4f797a128f.png">

Are there any problems with my operation?

**Comment by cmdcolin** [comment]
@NElight this plugin actually cares about the capitalization of the plugin

Please call the folder name MyVariantViewer and reference it with that same capitalization in the plugins

Quite the weirdly rendered error though...

**Comment by cmdcolin** [comment]
@NElight did this fix your issue?

**Comment by NElight** [comment]
thanks! it is ok now.

**Comment by NElight** [comment]
it is useful

**Comment by cmdcolin** [comment]
@NElight thanks for letting me know, means a lot. We will have to make a new version of this plugin for jbrowse 2 now :)

**Comment by cmdcolin** [comment]
Oh actually this plugin already was started for jbrowse 2, see here https://github.com/cmdcolin/jbrowse-plugin-biothings-api

Only works with mygene.info, not myvariant.info just yet
